version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SQL_SERVER_HOST=sql-server
      - SQL_SERVER_PORT=1433
      - SQL_SERVER_DB=mydatabase
      - SQL_SERVER_USER=sa
      - SQL_SERVER_PASSWORD=YourPassword@123
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=YourPassword@123
      - ACCEPT_EULA=Y
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
